services:

  # https://hub.docker.com/r/technitium/dns-server
  dns:
    image: technitium/dns-server:latest
    restart: unless-stopped
    container_name: dns
    network_mode: host
    user: 1001:1001
    environment:
      DNS_SERVER_ADMIN_PASSWORD: ${SECRET}
    volumes:
    - ./dns:/etc/dns

  # https://hub.docker.com/r/jellyfin/jellyfin
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: 'unless-stopped'
    container_name: jellyfin
    user: 1002:1002
    ports:
    - "8096:8096/tcp"
    volumes:
    - ./jellyfin/config:/config
    - ./jellyfin/cache:/cache
    - ./jellyfin/media:/media

  # https://hub.docker.com/r/linuxserver/transmission
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    container_name: transmission
    network_mode: host
    environment:
      PUID: 1003
      PGID: 1003
    #ports:
    #- "10.42.0.1:9091:9091/tcp"
    volumes:
    - ./transmission/config:/config
    - ./transmission/downloads:/downloads
    - ./transmission/watch:/watch

  # https://hub.docker.com/r/vimagick/dante
  dante:
    image: vimagick/dante:latest
    restart: unless-stopped
    container_name: dante
    network_mode: "host"
    volumes:
    - ./dante:/etc/dante

  pac:
    image: ghcr.io/sontarru/pac:latest
    restart: unless-stopped
    container_name: pac
    user: 1005:1005
    volumes:
    - ./pac:/app/wwwroot
    ports:
    - "10.42.0.1:8080:8080/tcp"

