services:

  # https://hub.docker.com/r/jellyfin/jellyfin
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: 'unless-stopped'
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./jellyfin/media:/media

  # https://hub.docker.com/r/linuxserver/transmission
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    container_name: transmission
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - "9091:9091/tcp"
    volumes:
      - ./transmission/config:/config
      - ./transmission/downloads:/downloads
      - ./transmission/watch:/watch

  # https://hub.docker.com/r/technitium/dns-server
  dns:
    image: technitium/dns-server:latest
    restart: unless-stopped
    container_name: dns
    network_mode: "host"
    environment:
      DNS_SERVER_ADMIN_PASSWORD: ${SECRET}
    volumes:
      - ./dns:/etc/dns
