services:

  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: 'unless-stopped'
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./jellyfin/media:/media

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    container_name: transmission
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Moscow
      # - TRANSMISSION_WEB_HOME= #optional
      # - USER: rnovo
      # - PASS= #optional
      # - WHITELIST= #optional
      # - PEERPORT= #optional
      # - HOST_WHITELIST= #optional
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - ./transmission/config:/config
      - ./transmission/downloads:/downloads
      - ./transmission/watch:/watch

# dnsmasq:
#   image: ghcr.io/sontarru/dnsmasq:latest
#   restart: unless-stopped
#   container_name: dnsmasq
#   network_mode: host
#   volumes:
#     - /etc/dnsmasq.conf:/etc/dnsmasq.conf
#     - /etc/hosts:/etc/hosts
#   cap_add:
#     - NET_ADMIN

  dns:
    image: technitium/dns-server:latest
    restart: unless-stopped
    container_name: dns
    # For DHCP deployments, use "host" network mode and remove all the port mappings, including the ports array by commenting them
    network_mode: "host"
    environment:
      DNS_SERVER_ADMIN_PASSWORD: ${SECRET} #DNS web console admin user password.
    volumes:
      - ./dns:/etc/dns

